spring:
  application:
    name: service-gateway-server
  profiles:
    active: development

---
# configuration: common(default)
spring:
   cloud:
      config:
         enabled: true
         uri: http://localhost:7777

---
# configuration: development
spring:
   config:
      activate:
         on-profile: development
      import: optional:configserver:http://localhost:7777

---
# configuration: production
spring:
   config:
      activate:
         on-profile: production
      import: optional:configserver:http://192.168.64.2:7777